### ISSUE TITLE
CMake to run Examples

### ISSUE THREAD

**Issue by mastunibayreuth** [spacy-dev/Spacy#29]
We had to hard code the paths in   CMakeList.txt to run the examples because otherwise the respective CMake files cannot be found

Diff for CMakeList to run simple Examples:

< ### set(Spacy_DIR ${CMAKE_SOURCE_DIR}/../../../../)
< ### set(Spacy_DIR /home/bt/bt304332/git-repos/Spacy/cmake)
< set(Spacy_DIR ${CMAKE_SOURCE_DIR}/../../../cmake)
< 
14,17c8
<     ### ${CMAKE_SOURCE_DIR}/cmake
<     ### ${CMAKE_SOURCE_DIR}/../../../../cmake
<     ${CMAKE_SOURCE_DIR}/../../../cmake
<     ### /home/bt/bt304332/git-repos/Spacy/cmake
---
>     ${CMAKE_SOURCE_DIR}/cmake

Any idea why this has to be done ?

**Comment by lubkoll** [comment]
What exactly is the problem if you don't do this? And which example did you try to compile?

**Comment by lubkoll** [comment]
Not reproducible.
